### ISSUE TITLE
_wdm_lib missing

### ISSUE THREAD

**Issue by soperjj** [timcera/wdmtoolbox#47]
Hi there, I just installed wdmtoolbox via pip into a conda environment. The _wdm_lib import from wdmutil.py appears to be causing some trouble when using wdm.listdsns. I am running Python 3.10 and wdmtoolbox version 16.0.4.

`ImportError: DLL load failed while importing _wdm_lib: The specified module could not be found.`

**Comment by timcera** [comment]
Even though I test the pip packages using Github workflows, somehow the install files don't include the _wdm_lib.dll.  I just tested the conda packages and they do work if you can work with a conda environment.  Hopefully that is a work-around until I fix the pip packages.

If all you need to do is **read** from wdm files, I put together a pure python package called hsfp_reader which might help.  hspf_reader is a much simpler package since it doesn't include any FORTRAN that has to be compiled.

Kind regards,
Tim

**Comment by timcera** [comment]
I just re-read your message, apologies for not catching it earlier, but you are already working in a conda environment.  I have almost all of my packages on conda-forge and so this should work for you...

```
pip uninstall wdmtoolbox
conda install -c conda-forge wdmtoolbox
```

**Comment by soperjj** [comment]
Thanks, that seemed to do the trick!
