### ISSUE TITLE
Missing values in a long dataset.

### ISSUE THREAD

**Issue by mishranurag** [timcera/wdmtoolbox#6]
I prepared a timeseries of a long-term dataset and saved it in a wdm file. Before saving the dataset, I filled all missing values using nearby station or interpolation. However, after filling the values, the WDMDataset still seems to have some missing values. I checked in the pandas dataframe and there is a valid value at these timestamps. The image below shows the missing values in the WDM file although they were filled in the original dataframe.

![image](https://user-images.githubusercontent.com/15083239/79401347-ae2ae200-7f3d-11ea-9bd5-9a1f4f5c5790.png)

**Comment by timcera** [comment]
Anurag,

Would you be willing to share your script and data?  If you don't want to post it here, send it to me at tim@cerazone.net.

Is is an hourly or daily dataset?

Kindest regards,
Tim

**Comment by mishranurag** [comment]
Sure.

Here are the files.

https://www.dropbox.com/sh/y74mpyd7yad4kdl/AACZTco8_-UGoyap8pVJl5k2a?dl=0

Thank you
~A
***********************************
Anurag Mishra

**Comment by mishranurag** [comment]
Looks like the original dataset skipped an hour due to time change. That probably caused the issue.

**Comment by timcera** [comment]
I thought that wdmtoolbox would be robust enough to handle that.  Haven't
got a chance to look at it yet, not until next week because of other
deadlines.  Now a duplicate time stamp when daylight savings falls back
does confuse it.  That is why I have in tstoolbox a "clean=True" option in
all of the functions, which will remove duplicate time stamps.

Looking at your script I have some utilities that might help.  For example,

    df = tstoolbox.fill("from", from_columns=[1,2,3], to_columns=[4,5,6],
input_ts=inputdf)

Would fill the missing values in columns 4, 5, and 6 with values in turn
from columns 1, 2, and 3.

I also have started writing a "mettoolbox" that has disaggregation and
evaporation functions.  Only evaporation function right now is Hargreaves.

    from mettoolbox import mettoolbox as mt
    df = mt.pet.hargreaves(24,
                           1,
                           2,
                           ["degF", "degF"],
                           input_ts="tmin_tmax_data.csv")
    # 24 is the latitude
    # 1 is column in the dataset that represents the minimum daily
temperature
    # 2 is column in the dataset that represents the maximum daily
temperature
    # ["degF", "degF"] are the units of the minimum and maximum daily
temperature

Also to disaggregate:

    from mettoolbox import mettoolbox as mt
    df_hourly = mettoolbox.disaggregate.temperature("sine_mean",
                                                    ["degC", "degC"],
                                                    temp_min_col=1,
                                                    temp_max_col=2,
                                                    input_ts=df_daily)

**Comment by mishranurag** [comment]
Thanks Tim.

Feel free to use the code that I wrote and shared on LinkedIn blog to
improve the library that you have.

On that note, do you have a library to edit and save the UCI file back
again?
~A
***********************************
Anurag Mishra

**Comment by timcera** [comment]
Thank you for the offer.  I think I will add your evaporation routine to
mettoolbox.

No library to work with uci files.  That would be nice. I have a lot of
code scattered about that reads uci files, but nothing gathered together in
a library.

Kindest regards,
Tim
